import {
  Student,
  Parent,
  Teacher,
  AttendanceRecord,
  TimetablePeriod,
  HomeworkItem,
  AssignmentSubmission,
  ExamRecord,
  StudentMarks,
  FeeStructure,
  FeeTransaction,
  BusRoute,
  VisitorPass,
  ClinicVisit,
  LibraryBook,
  BroadcastAnnouncement,
} from '@/types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-10101',
    admissionNo: 'VMPS-2020-0412',
    rollNumber: '10101',
    firstName: 'Aarav',
    lastName: 'Sharma',
    fullName: 'Aarav Sharma',
    gender: 'male',
    dob: '2010-08-14',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. Rajesh Sharma',
    parentPhone: '+91 98112 44321',
    parentEmail: 'rajesh.sharma@gmail.com',
    bloodGroup: 'B+',
    address: 'Flat 402, Shivalik Apartments, Sector 6, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 6 Market Stop',
    isHostelite: false,
    overallAttendancePercentage: 94.2,
    feeStatus: 'pending',
    pendingFeeAmount: 28500,
  },
  {
    id: 'std-10102',
    admissionNo: 'VMPS-2020-0419',
    rollNumber: '10102',
    firstName: 'Diya',
    lastName: 'Patel',
    fullName: 'Diya Patel',
    gender: 'female',
    dob: '2010-11-03',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. Vikram Patel',
    parentPhone: '+91 98710 55432',
    parentEmail: 'vikram.patel@yahoo.com',
    bloodGroup: 'O+',
    address: 'B-12, Sector 11, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 11 Metro Station Stop',
    isHostelite: false,
    overallAttendancePercentage: 97.5,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  },
  {
    id: 'std-10103',
    admissionNo: 'VMPS-2020-0430',
    rollNumber: '10103',
    firstName: 'Rohan',
    lastName: 'Iyer',
    fullName: 'Rohan Iyer',
    gender: 'male',
    dob: '2010-04-22',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. S. Iyer',
    parentPhone: '+91 99104 22334',
    parentEmail: 's.iyer@tcs.com',
    bloodGroup: 'A+',
    address: 'Pocket 1, Sector 9, Dwarka, New Delhi',
    busRouteId: 'route-05',
    busStopName: 'Sector 9 Mother Dairy',
    isHostelite: false,
    overallAttendancePercentage: 91.0,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  },
  {
    id: 'std-10104',
    admissionNo: 'VMPS-2020-0442',
    rollNumber: '10104',
    firstName: 'Priya',
    lastName: 'Nair',
    fullName: 'Priya Nair',
    gender: 'female',
    dob: '2010-09-19',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mrs. Jayasree Nair',
    parentPhone: '+91 98188 77665',
    parentEmail: 'jayasree.nair@gmail.com',
    bloodGroup: 'AB+',
    address: 'Plot 45, Sector 14, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 14 School Gate',
    isHostelite: false,
    overallAttendancePercentage: 96.0,
    feeStatus: 'partial',
    pendingFeeAmount: 14250,
  },
  {
    id: 'std-10105',
    admissionNo: 'VMPS-2020-0455',
    rollNumber: '10105',
    firstName: 'Vihaan',
    lastName: 'Mukherjee',
    fullName: 'Vihaan Mukherjee',
    gender: 'male',
    dob: '2010-02-11',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Dr. Debabrata Mukherjee',
    parentPhone: '+91 98101 33445',
    parentEmail: 'dmukherjee@aiims.edu',
    bloodGroup: 'B-',
    address: 'Tower 3, AIIMS Staff Quarters, New Delhi',
    busRouteId: 'route-08',
    busStopName: 'Janakpuri Bus Stand',
    isHostelite: false,
    overallAttendancePercentage: 88.5,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  },
  {
    id: 'std-10106',
    admissionNo: 'VMPS-2020-0461',
    rollNumber: '10106',
    firstName: 'Tanvi',
    lastName: 'Reddy',
    fullName: 'Tanvi Reddy',
    gender: 'female',
    dob: '2010-06-30',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. K. V. Reddy',
    parentPhone: '+91 97115 88990',
    parentEmail: 'kvreddy@bsnl.in',
    bloodGroup: 'O-',
    address: 'C-89, Sector 7, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 7 Market',
    isHostelite: false,
    overallAttendancePercentage: 98.2,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  },
  {
    id: 'std-10107',
    admissionNo: 'VMPS-2020-0472',
    rollNumber: '10107',
    firstName: 'Aditya',
    lastName: 'Verma',
    fullName: 'Aditya Verma',
    gender: 'male',
    dob: '2010-12-05',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. Sunil Verma',
    parentPhone: '+91 98114 66554',
    parentEmail: 'sverma@airindia.in',
    bloodGroup: 'A-',
    address: 'Air India Officers Enclave, Vasant Kunj, New Delhi',
    isHostelite: true,
    hostelRoom: 'Room 204 - Tagore Bhawan',
    overallAttendancePercentage: 92.4,
    feeStatus: 'overdue',
    pendingFeeAmount: 38500,
  },
  {
    id: 'std-10108',
    admissionNo: 'VMPS-2020-0480',
    rollNumber: '10108',
    firstName: 'Ananya',
    lastName: 'Joshi',
    fullName: 'Ananya Joshi',
    gender: 'female',
    dob: '2010-07-17',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mrs. Meenakshi Joshi',
    parentPhone: '+91 98991 22331',
    parentEmail: 'meenakshi.joshi@pnb.co.in',
    bloodGroup: 'B+',
    address: 'Sector 4, Pocket 2, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 4 Community Centre',
    isHostelite: false,
    overallAttendancePercentage: 95.8,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  },
  {
    id: 'std-10109',
    admissionNo: 'VMPS-2020-0491',
    rollNumber: '10109',
    firstName: 'Ishaan',
    lastName: 'Gupta',
    fullName: 'Ishaan Gupta',
    gender: 'male',
    dob: '2010-01-25',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. Manish Gupta',
    parentPhone: '+91 98109 99887',
    parentEmail: 'manish.gupta@delhicourts.nic.in',
    bloodGroup: 'O+',
    address: 'Judicial Enclave, Sector 10, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 10 District Court',
    isHostelite: false,
    overallAttendancePercentage: 86.4,
    feeStatus: 'pending',
    pendingFeeAmount: 28500,
  },
  {
    id: 'std-10110',
    admissionNo: 'VMPS-2020-0502',
    rollNumber: '10110',
    firstName: 'Meera',
    lastName: 'Sundaram',
    fullName: 'Meera Sundaram',
    gender: 'female',
    dob: '2010-05-14',
    class: '10',
    section: 'A',
    classSection: '10-A',
    academicYear: '2026-2027',
    parentName: 'Mr. N. Sundaram',
    parentPhone: '+91 98110 11223',
    parentEmail: 'nsundaram@delhiuniversity.ac.in',
    bloodGroup: 'AB-',
    address: 'Faculty Quarters, NSUT Campus, Sector 3, Dwarka',
    busRouteId: 'route-12',
    busStopName: 'NSUT Main Gate',
    isHostelite: false,
    overallAttendancePercentage: 99.1,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  },
  // Sibling in Class 6-B for Parent Multi-Child demo
  {
    id: 'std-06115',
    admissionNo: 'VMPS-2024-0892',
    rollNumber: '06115',
    firstName: 'Ananya',
    lastName: 'Sharma',
    fullName: 'Ananya Sharma',
    gender: 'female',
    dob: '2014-03-29',
    class: '6',
    section: 'B',
    classSection: '6-B',
    academicYear: '2026-2027',
    parentName: 'Mr. Rajesh Sharma',
    parentPhone: '+91 98112 44321',
    parentEmail: 'rajesh.sharma@gmail.com',
    bloodGroup: 'B+',
    address: 'Flat 402, Shivalik Apartments, Sector 6, Dwarka, New Delhi',
    busRouteId: 'route-12',
    busStopName: 'Sector 6 Market Stop',
    isHostelite: false,
    overallAttendancePercentage: 96.8,
    feeStatus: 'paid',
    pendingFeeAmount: 0,
  }
];

export const INITIAL_PARENTS: Parent[] = [
  {
    id: 'par-01',
    fatherName: 'Mr. Rajesh Sharma',
    motherName: 'Mrs. Sunita Sharma',
    primaryContact: '+91 98112 44321',
    email: 'rajesh.sharma@gmail.com',
    occupation: 'Director, Tech Consulting',
    children: [
      {
        studentId: 'std-10101',
        studentName: 'Aarav Sharma',
        classSection: '10-A',
        rollNumber: '10101',
      },
      {
        studentId: 'std-06115',
        studentName: 'Ananya Sharma',
        classSection: '6-B',
        rollNumber: '06115',
      },
    ],
  },
  {
    id: 'par-02',
    fatherName: 'Mr. Vikram Patel',
    motherName: 'Mrs. Bhavna Patel',
    primaryContact: '+91 98710 55432',
    email: 'vikram.patel@yahoo.com',
    occupation: 'Senior Chartered Accountant',
    children: [
      {
        studentId: 'std-10102',
        studentName: 'Diya Patel',
        classSection: '10-A',
        rollNumber: '10102',
      },
    ],
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'tch-01',
    employeeCode: 'EMP-TCH-084',
    name: 'Mrs. Lakshmi Raman',
    email: 'l.raman@vidyamandir.edu.in',
    phone: '+91 98103 44556',
    designation: 'Senior PGT Mathematics & Head of Department',
    qualification: 'M.Sc. Mathematics (DU), B.Ed, M.Phil',
    department: 'Mathematics',
    isClassTeacher: true,
    classSection: '10-A',
    subjects: ['Mathematics (Standard)', 'Applied Mathematics'],
    classes: ['10-A', '10-B', '11-A', '12-A'],
  },
  {
    id: 'tch-02',
    employeeCode: 'EMP-TCH-042',
    name: 'Mr. K. Venkatraman',
    email: 'k.venkatraman@vidyamandir.edu.in',
    phone: '+91 98110 99881',
    designation: 'PGT Physics & Science Coordinator',
    qualification: 'M.Sc. Physics (IIT Delhi), B.Ed',
    department: 'Science',
    isClassTeacher: true,
    classSection: '11-A',
    subjects: ['Physics', 'Science 10'],
    classes: ['10-A', '11-A', '12-A'],
  },
  {
    id: 'tch-03',
    employeeCode: 'EMP-TCH-061',
    name: 'Dr. Sunita Deshmukh',
    email: 's.deshmukh@vidyamandir.edu.in',
    phone: '+91 98712 33441',
    designation: 'PGT Chemistry & Lab In-charge',
    qualification: 'Ph.D. Chemistry, M.Sc. (JNU), B.Ed',
    department: 'Science',
    isClassTeacher: true,
    classSection: '11-B',
    subjects: ['Chemistry'],
    classes: ['10-A', '11-B', '12-A'],
  },
  {
    id: 'tch-04',
    employeeCode: 'EMP-TCH-099',
    name: 'Mr. Alok Saxena',
    email: 'a.saxena@vidyamandir.edu.in',
    phone: '+91 99114 77661',
    designation: 'PGT Computer Science & IT Administrator',
    qualification: 'MCA, B.Tech CS',
    department: 'Computer Science & AI',
    isClassTeacher: true,
    classSection: '10-B',
    subjects: ['Computer Applications & AI', 'Informatics Practices'],
    classes: ['10-A', '10-B', '11-A', '12-A'],
  },
  {
    id: 'tch-05',
    employeeCode: 'EMP-TCH-055',
    name: 'Mrs. P. Ananthalakshmi',
    email: 'p.anantha@vidyamandir.edu.in',
    phone: '+91 98118 22339',
    designation: 'TGT English & Cultural Committee Head',
    qualification: 'M.A. English Literature, B.Ed',
    department: 'Languages',
    isClassTeacher: true,
    classSection: '8-C',
    subjects: ['English Language & Literature'],
    classes: ['8-C', '10-A', '10-B'],
  },
];

export const TODAY_TIMETABLE_10A: TimetablePeriod[] = [
  { periodNumber: 1, startTime: '08:00 AM', endTime: '08:45 AM', subject: 'Mathematics', teacherName: 'Mrs. Lakshmi Raman', roomNumber: 'Room 204' },
  { periodNumber: 2, startTime: '08:45 AM', endTime: '09:30 AM', subject: 'Physics (Science)', teacherName: 'Mr. K. Venkatraman', roomNumber: 'Physics Lab 1' },
  { periodNumber: 3, startTime: '09:30 AM', endTime: '10:15 AM', subject: 'English Literature', teacherName: 'Mrs. P. Ananthalakshmi', roomNumber: 'Room 204' },
  { periodNumber: 4, startTime: '10:15 AM', endTime: '10:35 AM', subject: 'Recess / Morning Break', teacherName: 'Floor Supervision', roomNumber: 'Courtyard' },
  { periodNumber: 5, startTime: '10:35 AM', endTime: '11:20 AM', subject: 'Chemistry (Science)', teacherName: 'Dr. Sunita Deshmukh', roomNumber: 'Chem Lab 2' },
  { periodNumber: 6, startTime: '11:20 AM', endTime: '12:05 PM', subject: 'Social Science', teacherName: 'Mr. Rajeshwar Rao', roomNumber: 'Room 204' },
  { periodNumber: 7, startTime: '12:05 PM', endTime: '12:50 PM', subject: 'Computer Applications & AI', teacherName: 'Mr. Alok Saxena', roomNumber: 'Computer Lab 3' },
  { periodNumber: 8, startTime: '12:50 PM', endTime: '01:30 PM', subject: 'Physical Education / Sports', teacherName: 'Coach Satish Pal', roomNumber: 'Main Sports Ground' },
];

export const INITIAL_ATTENDANCE_10A: AttendanceRecord[] = [
  { id: 'att-01', studentId: 'std-10101', studentName: 'Aarav Sharma', rollNumber: '10101', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:46 AM' },
  { id: 'att-02', studentId: 'std-10102', studentName: 'Diya Patel', rollNumber: '10102', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:42 AM' },
  { id: 'att-03', studentId: 'std-10103', studentName: 'Rohan Iyer', rollNumber: '10103', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:50 AM' },
  { id: 'att-04', studentId: 'std-10104', studentName: 'Priya Nair', rollNumber: '10104', classSection: '10-A', date: '2026-09-25', status: 'late', checkInTime: '08:12 AM', remarks: 'Late due to metro line delay' },
  { id: 'att-05', studentId: 'std-10105', studentName: 'Vihaan Mukherjee', rollNumber: '10105', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:44 AM' },
  { id: 'att-06', studentId: 'std-10106', studentName: 'Tanvi Reddy', rollNumber: '10106', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:41 AM' },
  { id: 'att-07', studentId: 'std-10107', studentName: 'Aditya Verma', rollNumber: '10107', classSection: '10-A', date: '2026-09-25', status: 'absent', remarks: 'Sick leave intimation via parent email' },
  { id: 'att-08', studentId: 'std-10108', studentName: 'Ananya Joshi', rollNumber: '10108', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:48 AM' },
  { id: 'att-09', studentId: 'std-10109', studentName: 'Ishaan Gupta', rollNumber: '10109', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:52 AM' },
  { id: 'att-10', studentId: 'std-10110', studentName: 'Meera Sundaram', rollNumber: '10110', classSection: '10-A', date: '2026-09-25', status: 'present', checkInTime: '07:38 AM' },
];

export const INITIAL_HOMEWORK: HomeworkItem[] = [
  {
    id: 'hw-01',
    title: 'Chapter 8: Quadratic Equations - Exercise 4.3 Word Problems',
    description: 'Solve questions 1 through 9 from NCERT textbook Exercise 4.3 in homework notebook. Show complete step-by-step discriminant calculations.',
    classSection: '10-A',
    subject: 'Mathematics',
    teacherName: 'Mrs. Lakshmi Raman',
    assignedDate: '2026-09-24',
    dueDate: '2026-09-27',
    attachments: ['NCERT_Ch8_Quadratic_Practice_Worksheet.pdf'],
    totalSubmissions: 31,
    totalStudents: 36,
  },
  {
    id: 'hw-02',
    title: 'Light Reflection & Refraction - Ray Diagrams Practice',
    description: 'Draw accurate ray diagrams for concave and convex mirrors across all 6 object positions on plain A4 sheets with sign conventions.',
    classSection: '10-A',
    subject: 'Science (Physics)',
    teacherName: 'Mr. K. Venkatraman',
    assignedDate: '2026-09-23',
    dueDate: '2026-09-26',
    attachments: ['Mirror_Lens_RayDiagram_Guide.pdf'],
    totalSubmissions: 28,
    totalStudents: 36,
  },
  {
    id: 'hw-03',
    title: 'Formal Letter to Municipal Commissioner (Civic Issues)',
    description: 'Draft a 150-word formal letter highlighting poor drainage in monsoon in your locality as per CBSE 2026 marking scheme.',
    classSection: '10-A',
    subject: 'English Language',
    teacherName: 'Mrs. P. Ananthalakshmi',
    assignedDate: '2026-09-22',
    dueDate: '2026-09-25',
    totalSubmissions: 35,
    totalStudents: 36,
  },
  {
    id: 'hw-04',
    title: 'SQL DDL & DML Commands Practice on Student Database',
    description: 'Write CREATE TABLE, INSERT INTO, UPDATE and SELECT queries with WHERE clause as demonstrated in Computer Lab 3.',
    classSection: '10-A',
    subject: 'Computer Applications',
    teacherName: 'Mr. Alok Saxena',
    assignedDate: '2026-09-20',
    dueDate: '2026-09-28',
    attachments: ['MySQL_Class10_Assignment_Script.sql'],
    totalSubmissions: 24,
    totalStudents: 36,
  },
];

export const INITIAL_ASSIGNMENT_SUBMISSIONS: AssignmentSubmission[] = [
  {
    id: 'sub-01',
    assignmentId: 'hw-01',
    studentId: 'std-10101',
    studentName: 'Aarav Sharma',
    rollNumber: '10101',
    submittedAt: '2026-09-24 07:15 PM',
    status: 'graded',
    marksObtained: 19,
    maxMarks: 20,
    teacherFeedback: 'Excellent clarity in quadratic formula derivations. Review calculation in question 6.',
  },
  {
    id: 'sub-02',
    assignmentId: 'hw-01',
    studentId: 'std-10102',
    studentName: 'Diya Patel',
    rollNumber: '10102',
    submittedAt: '2026-09-24 06:40 PM',
    status: 'graded',
    marksObtained: 20,
    maxMarks: 20,
    teacherFeedback: 'Flawless work! Very neat presentation.',
  },
  {
    id: 'sub-03',
    assignmentId: 'hw-01',
    studentId: 'std-10104',
    studentName: 'Priya Nair',
    rollNumber: '10104',
    submittedAt: '2026-09-24 09:20 PM',
    status: 'submitted',
    maxMarks: 20,
  },
];

export const INITIAL_EXAMS: ExamRecord[] = [
  {
    id: 'exam-hy-2026-math',
    title: 'Half-Yearly Examination 2026',
    academicYear: '2026-2027',
    classSection: '10-A',
    subject: 'Mathematics (Standard)',
    examDate: '2026-09-18',
    maxMarks: 80,
    passingMarks: 27,
    status: 'published',
  },
  {
    id: 'exam-hy-2026-sci',
    title: 'Half-Yearly Examination 2026',
    academicYear: '2026-2027',
    classSection: '10-A',
    subject: 'Science (Physics, Chem, Bio)',
    examDate: '2026-09-20',
    maxMarks: 80,
    passingMarks: 27,
    status: 'published',
  },
  {
    id: 'exam-hy-2026-eng',
    title: 'Half-Yearly Examination 2026',
    academicYear: '2026-2027',
    classSection: '10-A',
    subject: 'English Language & Literature',
    examDate: '2026-09-22',
    maxMarks: 80,
    passingMarks: 27,
    status: 'published',
  },
  {
    id: 'exam-pb1-2026-math',
    title: 'Pre-Board Examination I',
    academicYear: '2026-2027',
    classSection: '10-A',
    subject: 'Mathematics (Standard)',
    examDate: '2026-11-15',
    maxMarks: 80,
    passingMarks: 27,
    status: 'scheduled',
  },
];

export const INITIAL_STUDENT_MARKS_10A_MATH: StudentMarks[] = [
  { id: 'sm-std-10101', studentId: 'std-10101', studentName: 'Aarav Sharma', rollNumber: '10101', marksObtained: 74, maxMarks: 80, grade: 'A1', remarks: 'Exceptional analytical capability in trigonometry and algebra.' },
  { id: 'sm-std-10102', studentId: 'std-10102', studentName: 'Diya Patel', rollNumber: '10102', marksObtained: 78, maxMarks: 80, grade: 'A1', remarks: 'Outstanding problem solving. Top rank candidate.' },
  { id: 'sm-std-10103', studentId: 'std-10103', studentName: 'Rohan Iyer', rollNumber: '10103', marksObtained: 68, maxMarks: 80, grade: 'A2', remarks: 'Strong fundamentals, needs more practice in coordinate geometry.' },
  { id: 'sm-std-10104', studentId: 'std-10104', studentName: 'Priya Nair', rollNumber: '10104', marksObtained: 71, maxMarks: 80, grade: 'B1', remarks: 'Good accuracy. Work on speed during timed sections.' },
  { id: 'sm-std-10105', studentId: 'std-10105', studentName: 'Vihaan Mukherjee', rollNumber: '10105', marksObtained: 62, maxMarks: 80, grade: 'B2', remarks: 'Consistent effort. Practice NCERT Exemplar questions.' },
  { id: 'sm-std-10106', studentId: 'std-10106', studentName: 'Tanvi Reddy', rollNumber: '10106', marksObtained: 76, maxMarks: 80, grade: 'A1', remarks: 'Very methodical and systematic proofs in geometry.' },
  { id: 'sm-std-10107', studentId: 'std-10107', studentName: 'Aditya Verma', rollNumber: '10107', marksObtained: 54, maxMarks: 80, grade: 'C1', remarks: 'Needs remedial guidance in quadratic equations.' },
  { id: 'sm-std-10108', studentId: 'std-10108', studentName: 'Ananya Joshi', rollNumber: '10108', marksObtained: 69, maxMarks: 80, grade: 'B1', remarks: 'Solid performance. Good test discipline.' },
  { id: 'sm-std-10109', studentId: 'std-10109', studentName: 'Ishaan Gupta', rollNumber: '10109', marksObtained: 58, maxMarks: 80, grade: 'C1', remarks: 'Requires regular homework submission and revision.' },
  { id: 'sm-std-10110', studentId: 'std-10110', studentName: 'Meera Sundaram', rollNumber: '10110', marksObtained: 79, maxMarks: 80, grade: 'A1', remarks: 'Class highest score. Commendable precision.' },
];

export const INITIAL_FEE_STRUCTURES: FeeStructure[] = [
  {
    id: 'fee-struct-10',
    classSection: '10-A',
    title: 'Class 10 Regular Academic Fee Structure 2026-27',
    annualTuition: 85500,
    developmentCharges: 12000,
    labCharges: 6000,
    termInstallments: [
      { termNumber: 1, title: 'Term 1 Installment (Due: 15 Apr 2026)', dueDate: '2026-04-15', amount: 28500 },
      { termNumber: 2, title: 'Term 2 Installment (Due: 15 Oct 2026)', dueDate: '2026-10-15', amount: 28500 },
      { termNumber: 3, title: 'Term 3 Installment (Due: 15 Jan 2027)', dueDate: '2027-01-15', amount: 28500 },
    ],
  },
];

export const INITIAL_FEE_TRANSACTIONS: FeeTransaction[] = [
  {
    id: 'txn-2026-0041',
    receiptNumber: 'VMPS/2026-27/REC-4891',
    studentId: 'std-10101',
    studentName: 'Aarav Sharma',
    classSection: '10-A',
    amountPaid: 28500,
    paymentMode: 'upi',
    transactionDate: '2026-04-12 11:24 AM',
    status: 'success',
    termTitle: 'Term 1 Installment (Academic Session 2026-27)',
    feeHeads: [
      { head: 'Tuition Fee (Quarter 1)', amount: 22500 },
      { head: 'Annual Development Charges', amount: 4000 },
      { head: 'Science & Computer Lab Charges', amount: 2000 },
    ],
  },
  {
    id: 'txn-2026-0082',
    receiptNumber: 'VMPS/2026-27/REC-4912',
    studentId: 'std-10102',
    studentName: 'Diya Patel',
    classSection: '10-A',
    amountPaid: 57000,
    paymentMode: 'net_banking',
    transactionDate: '2026-09-10 03:45 PM',
    status: 'success',
    termTitle: 'Term 1 & Term 2 Advance Settlement',
    feeHeads: [
      { head: 'Tuition Fee (Term 1 & 2)', amount: 45000 },
      { head: 'Development & Lab Charges', amount: 12000 },
    ],
  },
  {
    id: 'txn-2026-0105',
    receiptNumber: 'VMPS/2026-27/REC-5020',
    studentId: 'std-10103',
    studentName: 'Rohan Iyer',
    classSection: '10-A',
    amountPaid: 28500,
    paymentMode: 'credit_card',
    transactionDate: '2026-09-20 01:10 PM',
    status: 'success',
    termTitle: 'Term 2 Installment',
    feeHeads: [
      { head: 'Tuition Fee (Quarter 2)', amount: 22500 },
      { head: 'Transport Route 05 Fee', amount: 6000 },
    ],
  },
];

export const INITIAL_BUS_ROUTES: BusRoute[] = [
  {
    id: 'route-12',
    routeNumber: 'Route 12',
    routeName: 'Dwarka Sector 6 to Vidya Mandir Public School',
    busNumber: 'DL-01-AB-4592 (Tata Starbus 42-Seater)',
    capacity: 42,
    assignedStudents: 38,
    driverName: 'Mr. Ramesh Kumar',
    driverPhone: '+91 98112 34567',
    attendantName: 'Mr. Ram Singh',
    attendantPhone: '+91 98119 76543',
    currentStatus: 'on_route',
    currentLocationName: 'Approaching Sector 11 Metro Station (ETA 4 mins)',
    stops: [
      { stopId: 'st-01', stopName: 'Dwarka Mor Metro Gate 2', pickupTime: '06:55 AM', dropTime: '02:40 PM', studentsCount: 8, status: 'passed' },
      { stopId: 'st-02', stopName: 'Sector 6 DDA Market', pickupTime: '07:10 AM', dropTime: '02:25 PM', studentsCount: 11, status: 'passed' },
      { stopId: 'st-03', stopName: 'Sector 11 Metro Station', pickupTime: '07:22 AM', dropTime: '02:12 PM', studentsCount: 9, status: 'approaching' },
      { stopId: 'st-04', stopName: 'Sector 10 District Court Crossing', pickupTime: '07:32 AM', dropTime: '02:00 PM', studentsCount: 6, status: 'next' },
      { stopId: 'st-05', stopName: 'Sector 14 Vidya Mandir Main Gate', pickupTime: '07:45 AM', dropTime: '01:45 PM', studentsCount: 4, status: 'pending' },
    ],
  },
  {
    id: 'route-05',
    routeNumber: 'Route 05',
    routeName: 'Janakpuri West to Vidya Mandir Public School',
    busNumber: 'DL-01-XY-3180 (Ashok Leyland 40-Seater)',
    capacity: 40,
    assignedStudents: 36,
    driverName: 'Mr. Sukhdev Singh',
    driverPhone: '+91 98991 12345',
    attendantName: 'Mr. Manoj Kumar',
    attendantPhone: '+91 98995 54321',
    currentStatus: 'completed',
    currentLocationName: 'Arrived at School Parking Bay 05',
    stops: [
      { stopId: 'st-05-1', stopName: 'Janakpuri District Centre', pickupTime: '06:50 AM', dropTime: '02:45 PM', studentsCount: 12, status: 'passed' },
      { stopId: 'st-05-2', stopName: 'Uttam Nagar East', pickupTime: '07:05 AM', dropTime: '02:30 PM', studentsCount: 14, status: 'passed' },
      { stopId: 'st-05-3', stopName: 'School Main Gate', pickupTime: '07:40 AM', dropTime: '01:50 PM', studentsCount: 10, status: 'passed' },
    ],
  },
];

export const INITIAL_VISITOR_PASSES: VisitorPass[] = [
  {
    id: 'vp-01',
    passNumber: 'VP-2026-0814',
    visitorName: 'Mr. Anand Swaroop',
    phone: '+91 98114 55667',
    purpose: 'Admission Enquiry for Class 11 Science',
    meetingPerson: 'Admissions Officer (Room 102)',
    entryTime: '09:15 AM',
    status: 'active',
    vehicleNumber: 'DL-8C-AS-1102',
  },
  {
    id: 'vp-02',
    passNumber: 'VP-2026-0815',
    visitorName: 'Dr. (Mrs.) Ritu Sen',
    phone: '+91 98710 44321',
    purpose: 'CBSE Regional Inspection Committee Member',
    meetingPerson: 'Principal Dr. Arvind Swaminathan',
    entryTime: '10:00 AM',
    status: 'active',
  },
  {
    id: 'vp-03',
    passNumber: 'VP-2026-0812',
    visitorName: 'Mr. Surender Malhotra (S.K. Publishers)',
    phone: '+91 98102 77889',
    purpose: 'Delivery of CBSE sample papers & science manuals',
    meetingPerson: 'Librarian & Examination Cell',
    entryTime: '08:30 AM',
    exitTime: '09:20 AM',
    status: 'checked_out',
  },
];

export const INITIAL_CLINIC_VISITS: ClinicVisit[] = [
  {
    id: 'cln-01',
    studentName: 'Vihaan Mukherjee',
    classSection: '10-A',
    visitTime: '09:45 AM',
    symptoms: 'Mild headache and eye strain after laboratory session',
    treatment: 'Rest on clinic bed for 20 mins, cold compress applied, vitals normal (BP 110/72, Temp 98.4°F)',
    medicationGiven: 'Oral Paracetamol 250mg given with water with parent verbal consent',
    attendingNurse: 'Sister Anita Roy (RN)',
    parentNotified: true,
  },
  {
    id: 'cln-02',
    studentName: 'Tanvi Reddy',
    classSection: '10-A',
    visitTime: '11:30 AM',
    symptoms: 'Minor knee scrape during basketball practice',
    treatment: 'Wound cleaned with antiseptic betadine solution, sterile band-aid applied',
    medicationGiven: 'None required',
    attendingNurse: 'Sister Anita Roy (RN)',
    parentNotified: false,
  },
];

export const INITIAL_LIBRARY_BOOKS: LibraryBook[] = [
  {
    id: 'lib-01',
    isbn: '978-8174508126',
    title: 'Mathematics Textbook for Class X (NCERT Standard)',
    author: 'NCERT Curriculum Directorate',
    category: 'Mathematics',
    totalCopies: 45,
    availableCopies: 12,
    rackLocation: 'Section B, Rack 04',
  },
  {
    id: 'lib-02',
    isbn: '978-9351449553',
    title: 'Concepts of Physics (Volume 1 & 2)',
    author: 'Prof. H.C. Verma',
    category: 'Science (Physics)',
    totalCopies: 25,
    availableCopies: 7,
    rackLocation: 'Section C, Rack 02',
  },
  {
    id: 'lib-03',
    isbn: '978-0143424123',
    title: 'India After Gandhi: The History of the World\'s Largest Democracy',
    author: 'Ramachandra Guha',
    category: 'General Reference & History',
    totalCopies: 10,
    availableCopies: 6,
    rackLocation: 'Section H, Rack 01',
  },
  {
    id: 'lib-04',
    isbn: '978-9389845112',
    title: 'Computer Science with Python for CBSE Class 11 & 12',
    author: 'Sumita Arora',
    category: 'Computer Science',
    totalCopies: 30,
    availableCopies: 14,
    rackLocation: 'Section IT, Rack 05',
  },
];

export const INITIAL_ANNOUNCEMENTS: BroadcastAnnouncement[] = [
  {
    id: 'anc-01',
    title: 'CBSE Class 10 & 12 Pre-Board I Date-Sheet Released',
    content: 'The date-sheet for Pre-Board Examination I (Session 2026-27) has been scheduled commencing from November 15, 2026. Practical assessments will precede the written papers. Students are advised to collect syllabus blue-prints from their respective class teachers.',
    category: 'academic',
    targetAudience: 'all',
    publishedAt: '2026-09-24 04:30 PM',
    publishedBy: 'Controller of Examinations',
    priority: 'high',
  },
  {
    id: 'anc-02',
    title: 'Term 2 Fee Installment Due by October 15, 2026',
    content: 'Parents are kindly requested to remit Term 2 fees on or before October 15, 2026 through the Parent Mobile App or school bank counter to avoid late fine surcharge. Online payments generate instant digitally signed receipts.',
    category: 'fee',
    targetAudience: 'parents',
    publishedAt: '2026-09-22 10:00 AM',
    publishedBy: 'Accounts & Finance Directorate',
    priority: 'normal',
  },
  {
    id: 'anc-03',
    title: 'Route 12 Bus Timing Adjustment for Sector 11 Stop',
    content: 'Due to scheduled metro corridor resurfacing near Sector 11 Dwarka, Bus Route 12 will arrive 5 minutes earlier at 07:17 AM starting Monday. Please ensure students arrive at the stop promptly.',
    category: 'transport',
    targetAudience: 'parents',
    publishedAt: '2026-09-23 02:15 PM',
    publishedBy: 'Transport Department',
    priority: 'high',
  },
];
